In [1]:
from scan import register_pairwise_affine
from scan import register_groupwise_deformable
from scan import register_groupwise_affine
from scan import batch_nifti_to_stl

/Data/MEDICAL/3d/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))


In [ ]:
input_folder  = "/Data/MEDICAL/data/unregistered"
output_folder = "/Data/MEDICAL/data/registered"

In [ ]:
register_pairwise_affine(input_folder, which='all', output_folder=output_folder)

In [ ]:
register_groupwise_deformable(input_folder, which='all')

In [ ]:
register_groupwise_affine(input_folder, which=3, output_folder=output_folder)

In [2]:
batch_nifti_to_stl(input_folder='/Data/MEDICAL/data/registered_gpu', how_many='all')

Found 5 file(s) in '/Data/MEDICAL/data/registered_gpu'.
Processing 5 file(s). Outputs saved in the same folder.

[1/5]
Loading /Data/MEDICAL/data/registered_gpu/ATM_001_0000_R.nii.gz...

--- NIfTI File Inspection ---
Data Shape (Grid Dimensions): (512, 512, 679)
Voxel Size (mm): (np.float32(0.8203125), np.float32(0.8203125), np.float32(0.5))

Affine Matrix (Position in space):
[[ -0.8203125    0.           0.         222.17999268]
 [  0.          -0.8203125    0.          81.40000153]
 [  0.           0.           0.5        478.61999512]
 [  0.           0.           0.           1.        ]]

--- Data Value Analysis ---
Minimum Value: 0.0
Maximum Value: 0.9999999997671694

CONCLUSION: This is likely a **Segmentation Mask**.
It only contains these specific labels: [0. 1.]

--- Mesh Generation & Alignment ---
Applying Marching Cubes algorithm...
Constructing 3D Mesh Object...
Applying the full Affine Matrix spatial transformation...
Exporting Mesh...

Success! Spatially aligned mesh sa

[{'mesh': <trimesh.Trimesh(vertices.shape=(103869, 3), faces.shape=(207846, 3))>,
  'output_path': '/Data/MEDICAL/data/registered_gpu/ATM_001_0000_R_aligned.stl',
  'affine': array([[ -0.8203125 ,   0.        ,   0.        , 222.17999268],
         [  0.        ,  -0.8203125 ,   0.        ,  81.40000153],
         [  0.        ,   0.        ,   0.5       , 478.61999512],
         [  0.        ,   0.        ,   0.        ,   1.        ]]),
  'voxel_size': (np.float32(0.8203125),
   np.float32(0.8203125),
   np.float32(0.5)),
  'data_shape': (512, 512, 679),
  'is_segmentation': True},
 {'mesh': <trimesh.Trimesh(vertices.shape=(104282, 3), faces.shape=(209116, 3))>,
  'output_path': '/Data/MEDICAL/data/registered_gpu/ATM_002_0000_R_aligned.stl',
  'affine': array([[ -0.8203125 ,   0.        ,   0.        , 222.17999268],
         [  0.        ,  -0.8203125 ,   0.        ,  81.40000153],
         [  0.        ,   0.        ,   0.5       , 478.61999512],
         [  0.        ,   0.       

In [ ]:
import SimpleITK as sitk
import os
  
# os.makedirs("/Data/MEDICAL/data/distance_maps", exist_ok=True)
binary = sitk.ReadImage("/Data/MEDICAL/data/unregistered/ATM_005_0000.nii.gz")
binary = sitk.Cast(binary, sitk.sitkUInt8)
sdt    = sitk.SignedMaurerDistanceMap(binary, insideIsPositive=True, squaredDistance=False, useImageSpacing=True)
sitk.WriteImage(sdt, "/Data/MEDICAL/data/distance_maps/ATM_005_0000_sdt.nii.gz")